### PR TITLE
Update u2f.conf.sample

### PR DESCRIPTION
**Pull request by jasoncawood**
This is to match the changes from commit bf3a625d846e22ff0ac3abac386781e0c09ffcab

### CODE REVIEW

**Comment by roycewilliams** [comment]
Typo on this one - 0x0120 is repeated twice, instead of 0x0121

**Comment by jasoncawood** [comment]
My apologies, in my rush to get the commit submitted I failed to make sure it was complete.  I've fixed the duplication and recommitted.

**Comment by roycewilliams** [comment]
No worries - and thanks for the add! Out of curiosity - which device is this? Is it the new white Titan-branded USB-C 5C? Or something else?

**Comment by jasoncawood** [comment]
It is the USB-C security key from Google for their Google Cloud product.  It is noted on the packaging as Titan Security Key (YT1)

**Pull request merged**
