### PR TITLE
Update udev rules to support new Gnubby U2F device from Yubico.

### PR DESCRIPTION
**Pull request by jichu4n**
This adds product IDs for two U2F devices from Yubico to the udev rules:

1050:0200 Yubico.com U2F Gnubby
1050:0211 Yubico.com Gnubby

### CODE REVIEW

**Comment by klali** [comment]
Do you have both of these devices? Do they work with this library (the one with 0x211 should not work, don't know about 0x200)?

**Comment by jichu4n** [comment]
Yes, I do have both ([screenshot from `lsusb`](http://imgur.com/39wOLZJ)).

You were right - I just tested again by plugging in only one device at a time, and indeed only 0200 worked and 0211 didn't. I must've been confused :-/ I've updated the PR to only add 0200 to the udev rules.

(Tested with vanilla Ubuntu 17.04, udev 232, Chrome 60.0.3112.90.)

**Comment by klali** [comment]
Thanks, merging this. (the reason 0x0211 doesn't work is that it uses a different usb transport, vendor class, not hid).

**Comment by jichu4n** [comment]
Thanks! :D

**Pull request merged**
