### PR TITLE
Update 70-u2f.rules (New SoloKey: Somu)

### PR DESCRIPTION
**Pull request by mue-de**
Adding the new Solokey-Device (https://www.crowdsupply.com/solokeys/somu)

### CODE REVIEW

**Comment by klali** [comment]
Are you sure about that vid and pid? Searching for it seems to hint at a company named verbatim ltd and a flash drive product.

**Comment by roycewilliams** [comment]
FWIW, my Somu presents as vid 0x0483 (STMicroelectronics), pid 0xa2ca.

**Comment by mue-de** [comment]
Hello, 
On Freitag, 7. Februar 2020, 08:42:54 CET Royce Williams wrote:
> FWIW, my Somu presents as vid 0x0483 (STMicroelectronics), pid 0xa2ca.

That were the first items i saw (dmesg|tail), when i plugged it in, and it 
wasn't recognized by my Kubuntu System (Bionic Beaver). 

With exactly these items this FIDO2-Stick is working now.

Greetings 

Ewald

**Comment by mue-de** [comment]
That were the messages when i plugged in the new Somu FIDO2-Key:
```

muelux@muelux-NB77A-Helix:/etc/udev/rules.d$ dmesg|tail
[22156.597591] usb 3-2.1: USB disconnect, device number 10
[22157.842750] usb 3-2.1: new high-speed USB device number 12 using xhci_hcd
[22157.946872] usb 3-2.1: New USB device found, idVendor=18a5, idProduct=0302, bcdDevice= 1.00
[22157.946874] usb 3-2.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[22157.946876] usb 3-2.1: Product: STORE N GO
[22157.946877] usb 3-2.1: Manufacturer: Verbatim
[22157.946877] usb 3-2.1: SerialNumber: 07A20709C9CCB810
[22157.947840] usb-storage 3-2.1:1.0: USB Mass Storage device detected
[22157.948285] scsi host6: usb-storage 3-2.1:1.0
[22158.133745] usb 3-2.1: USB disconnect, device number 12
muelux@muelux-NB77A-Helix:/etc/udev/rules.d$
```

**Comment by roycewilliams** [comment]
This doesn't make sense. Solo and Somu do not present as USB storage.

This is what I see when I plug in my Somu:

```
[  +0.020643] usb 3-1: USB disconnect, device number 19
[  +0.475445] usb 3-1: new full-speed USB device number 20 using xhci_hcd
[  +0.217456] usb 3-1: New USB device found, idVendor=0483, idProduct=a2ca
[  +0.000003] usb 3-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  +0.000001] usb 3-1: Product: Solo 3.0.0
[  +0.000001] usb 3-1: Manufacturer: SoloKeys
[  +0.000001] usb 3-1: SerialNumber: [redacted]
[  +0.002110] hid-generic 0003:0483:A2CA.001A: hiddev0,hidraw4: USB HID v1.11 Device [SoloKeys Solo 3.0.0] on usb-0000:03:00.0-1/input0
```
Can you mount the drive as a filesystem?

**Comment by mue-de** [comment]
Am Freitag, 7. Februar 2020, 16:23:04 CET schrieb Royce Williams:
> This doesn't make sense. Solo and Somu do not present as USB storage.
> 
> This is what I see when I plug in my Somu:
> 
> ```
> [  +0.020643] usb 3-1: USB disconnect, device number 19
> [  +0.475445] usb 3-1: new full-speed USB device number 20 using xhci_hcd
> [  +0.217456] usb 3-1: New USB device found, idVendor=0483, idProduct=a2ca
> [  +0.000003] usb 3-1: New USB device strings: Mfr=1, Product=2,
> SerialNumber=3 [  +0.000001] usb 3-1: Product: Solo 3.0.0
> [  +0.000001] usb 3-1: Manufacturer: SoloKeys
> [  +0.000001] usb 3-1: SerialNumber: [redacted]
> [  +0.002110] hid-generic 0003:0483:A2CA.001A: hiddev0,hidraw4: USB HID
> v1.11 Device [SoloKeys Solo 3.0.0] on usb-0000:03:00.0-1/input0 ```
> Can you mount the drive as a filesystem?

No, you're right ; now, after the first plugin an applying the modified rules 
(like early posted) i see the same items for the somu-devive (maybe first a 
bootloader has to be activated?).

If you understand german, you can read my whole  notice (as '.pdf') applied in 
the appendix.
As i said, the stick first didn't function on any Website with WebAuthn; after 
applying my changes to the 70-rules... file with idVendor= '18a5' and 
idProduct= '0302' its no working on any WebSite.

Greetings 

Ewald

**Comment by mue-de** [comment]
Now i've tried the stick again with the unmodified ''70-u2f.rules''-file: i can't repeat the steps bringing up the device with 'idVendor=18a5' and 'idProduct=0302'; so it surely was my mistake.
The Stick is always recognized as 'idVendor=0483', 'idProduct=a2ca'
Sorry; we surely can delete that branch.

**Pull request closed without merging**
