### PR TITLE
Add Titan Security Key YT1 (USB-C)

### PR DESCRIPTION
**Pull request by varungupta3009**
Reference: https://support.google.com/titansecuritykey/answer/9148044

### CODE REVIEW

**Comment by klali** [comment]
What vendor and product id combinations do this device have?

Adding both vendor ids on one line doesn't really make sense to me, it is probably better to make separate lines.

**Comment by varungupta3009** [comment]
> What vendor and product id combinations do this device have?

One of the Vendor IDs is for the Old Google Titan Keys that were created in collaboration with Feitian, hence the same Vendor ID (096e) and Product IDs (0858, 085b). The other one is probably Google's own Vendor ID (for the new USB-C one made in collaboration with YubiCo). There are also multiple versions of the original Bluetooth Key Fobs (T1, T2, T3).

> Adding both vendor ids on one line doesn't really make sense to me, it is probably better to make separate lines.

I agree. But Google prefers them that way and I think it helps to keep all their devices on one line because they haven't named all their keys differently, or as different products. They just have Titan Security Keys and different model numbers for each kind.

But if you would like it, I'll split them.

**Comment by klali** [comment]
Neither of these should be for the Titan manufactured by Yubico, it has vendor id 0x1050 and productid 0x121

vendor 0x96e is Feitians vendor id, both of these product ids (0x858, 0x85b) are already present on line 32 with their other products.

Does adding this fix anything for you that doesn't work without it?

**Comment by varungupta3009** [comment]
Oh yup, you're right. My bad. I had a different version of the file (one from Google Support).

Closed.

**Pull request closed without merging**
