### PR TITLE
Cmake build script

### PR DESCRIPTION
**Pull request by dhenot**
As we wanted to be able to compile on Windows where autotools are difficult to get working, here is a simple alternative build script using cmake.

It also includes some fixes needed to compile with VS2008.

### CODE REVIEW

**Comment by klali** [comment]
Hello,
Would you mind splitting this up in functionally sepparated pull requests? some of them are complete nobrainers (like c89 compatibility) while other parts might need more discussion.

/klas

**Comment by dhenot** [comment]
Sure, I'm going to put the commits unrelated to cmake into a separate pull request

**Comment by dhenot** [comment]
This pull request now contains only cmake-related changes. I submitted another one for simple compilation fixes.

**Comment by klali** [comment]
Thanks for splitting them!

My thoughts on this: I don't really like having two build systems for the project. But on the other hand you have a problem that this solves which is a point in it's favor.
Right now I'm leaning towards merging this in parallel to the autotools based build system which will still be the projects "official" build system. Thoughts?

Another question, is the stdint.h file needed when we do the typedef of uint8_t, uint16_t & uint32_t for platforms where it's not available?

**Comment by dhenot** [comment]
I agree that you should keep autotools as the official build system, since the cmake one is untested on anything else than Windows, doesn't build the tests, and could probably be improved as this was my first time creating a cmake build.

On the other hand having it in the official repo could help people find this alternative more easily.

In any case, it will continue living in our forked repository.

Regarding stdint.h, if I remember correctly that's right. I don't expect it to be needed on many platforms except Visual Studio 2008 (which we plan to replace soon for a newer version) but since it's a public domain implementation I thought it wouldn't hurt.

**Comment by klali** [comment]
actually looking at the stdint.h we seem to already have that from gnulib.. though I guess those parts from gnulib need autotools to run which makes it not execute and generate a stdint.h

So is the typedefs enough for visualstudio 2008 or is a full stdint.h needed? can we reuse the stdint.h.in that is in gl ?

**Comment by dhenot** [comment]
I forgot to mention it but indeed I tried to have cmake generate a valid stdint.h from this gl/stdint.h.in, but this file needs a lot of autotools-defined values to be replaced so I dropped the idea.

I played a bit with this file and it seems the strict minimum we have to define is this:
```
typedef unsigned char   uint8_t;
typedef unsigned short  uint16_t;
typedef int  int32_t;
typedef unsigned   uint32_t;
typedef long long  int64_t;
```

I guess it could be possible to hack the CMakeList file to generate a minimal stdint.h file with this content when we don't find stdint.h. Would you like that ?

By the way, I just realized that the changes in `u2f-host/u2f-host.h` should have been in my other pull request, it's a fix for compiling on VS and unrelated to cmake at all.

**Comment by klali** [comment]
I'm thinking that u2f-host.h already defines:

  typedef unsigned char uint8_t;
  typedef unsigned short uint16_t;
  typedef unsigned int uint32_t;
  typedef unsigned long int uint64_t;

so it's a quite minimal addition there if we need more definitions (or move them around).

**Comment by dhenot** [comment]
Indeed, now that you're pointing at this I wonder what I was thinking ... I'll rework this to work completely without stdint.h and update this pull request. I probably won't have time for this before the week-end though.

**Comment by dhenot** [comment]
I tried to remove the additional stdint.h and simply add a typedef for int32_t and now I remember why I did it like this. There are a couple of unguarded `#include <stdint.h>`, one in gl/sha256.h, which I could change but I don't know if you are ok with doing changes in gl, and another in json-c/json_inttypes.h, which is a bigger problem since it's in a different project ... so I really needed a valid stdint.h file, not just one more typdef.

Since this is only necessary for old versions of visual studio which we should be able to upgrade very soon, I think it doesn't make sense to pollute your repo with this. I'm going to keep the stdint.h hack in a separate branch in my repo as long as we need it, and strip it from this pull request.

**Comment by dhenot** [comment]
Changes done. I rebased on my previously accepted pull request to make things simpler on my side.

**Comment by klali** [comment]
Great!

**Pull request merged**
